server {
  port = 8080
}

database {
  url = "jdbc:postgresql://localhost:5432/eilaji_db"
  user = "eilaji"
  password = "eilaji_password_change_in_production"
  driver = "org.postgresql.Driver"
  poolSize = 10
  seed-on-startup = true  # SET TO TRUE ONLY FOR DEV/TESTING
}

logging {
  sqlLogging = false
}

redis {
  url = "redis://localhost:6379"
}

minio {
  endpoint = "http://localhost:9000"
  accessKey = "eilaji_minio_admin"
  secretKey = "eilaji_minio_password_change_in_production"
  region = "us-east-1"
  buckets {
    prescriptions = "prescriptions"
    medicineImages = "medicine-images"
    pharmacyImages = "pharmacy-images"
    userAvatars = "user-avatars"
  }
}

jwt {
  secret = "your-super-secret-jwt-key-change-in-production-minimum-32-characters-long"
  issuer = "eilaji-backend"
  audience = "eilaji-client"
  realm = "Eilaji API"
  expiresIn = 3600000
  refreshExpiresIn = 2592000000
}

eilaji-plus {
  baseUrl = ""
  apiKey = ""
}
